project: 
  type: website

website:
  title: "So. FREMONT CAR WASH"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://1ramirez7.github.io/Carwash1
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "So. FREMONT CAR WASH©"
    right: 
      - icon: linkedin
        href: linkedin.com/in/eduardo-ramirez-lds

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "So. FREMONT CAR WASH"
        file: resume.qmd
      
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
